name: Geyser Actions
description: A collection of GitHub Actions for GeyserMC projects.

runs:
  using: composite
  steps:
  - run: |
      echo "::error::The path 'GeyserMC/actions' is not a valid action. Please use 'GeyserMC/actions/release' or 'GeyserMC/actions/discord'."
      exit 1
    shell: bash

branding:
  icon: droplet
  color: blue