name: setup-gradle-composite
description: An action to set up a Gradle environment with the checked-out repository, Java, and Gradle wrapper validation.
inputs:
    checkout_repository:
        description: The repository to checkout.
        required: false
        default: '${{ github.repository }}'
    checkout_ref:
        description: The ref to checkout.
        required: false
    checkout_submodules:
        description: Whether to checkout submodules.
        required: false
        default: recursive
    checkout_fetch-depth:
        description: The depth to fetch the repository.
        required: false
    setup-java_java-version:
        description: The Java version to use.
        required: true
    setup-java_distribution:
        description: The Java distribution to use.
        required: false
        default: temurin
    setup-gradle_cache-read-only:
        description: Whether to make the Gradle cache read-only.
        required: false
    setup-gradle_gradle-home-cache-cleanup:
        description: Whether to clean up the Gradle home cache.
        required: false
        default: 'true'
runs:
    using: composite
    steps:
        - name: Checkout Repository and Submodules
          uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
          with:
              repository: '${{ inputs.checkout_repository }}'
              ref: '${{ inputs.checkout_ref }}'
              submodules: '${{ inputs.checkout_submodules }}'
              fetch-depth: '${{ inputs.checkout_fetch-depth }}'
              persist-credentials: false
        - name: Setup Java
          uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # v5.4.0
          with:
              distribution: '${{ inputs.setup-java_distribution }}'
              java-version: '${{ inputs.setup-java_java-version }}'
        - name: Setup Gradle
          uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0
          with:
              # cache-read-only: '${{ inputs.setup-gradle_cache-read-only }}'
              # gradle-home-cache-cleanup: '${{ inputs.setup-gradle_gradle-home-cache-cleanup }}'
              cache-disabled: true
