name: setup-gradle-composite
description: An action to set up a Gradle environment with the checked-out repository, Java, and Gradle wrapper validation.
inputs:
    checkout_repository:
        description: The repository to checkout.
        required: false
        default: '${{ github.repository }}'
    checkout_ref:
        description: The ref to checkout.
        required: false
    checkout_submodules:
        description: Whether to checkout submodules.
        required: false
        default: recursive
    checkout_fetch-depth:
        description: The depth to fetch the repository.
        required: false
    setup-java_java-version:
        description: The Java version to use.
        required: true
    setup-java_distribution:
        description: The Java distribution to use.
        required: false
        default: temurin
    setup-gradle_cache-read-only:
        description: Whether to make the Gradle cache read-only.
        required: false
    setup-gradle_gradle-home-cache-cleanup:
        description: Whether to clean up the Gradle home cache.
        required: false
        default: true
runs:
    using: composite
    steps:
        - name: Checkout Repository and Submodules
          uses: actions/checkout@09d2acae674a48949e3602304ab46fd20ae0c42f # v4.4.1
          with:
              repository: '${{ inputs.checkout_repository }}'
              ref: '${{ inputs.checkout_ref }}'
              submodules: '${{ inputs.checkout_submodules }}'
              fetch-depth: '${{ inputs.checkout_fetch-depth }}'
              persist-credentials: false
        - name: Setup Java
          uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
          with:
              distribution: '${{ inputs.setup-java_distribution }}'
              java-version: '${{ inputs.setup-java_java-version }}'
        - name: Setup Gradle
          uses: gradle/actions/setup-gradle@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
          with:
              # cache-read-only: '${{ inputs.setup-gradle_cache-read-only }}'
              # gradle-home-cache-cleanup: '${{ inputs.setup-gradle_gradle-home-cache-cleanup }}'
              cache-disabled: true
