name: Release

on:
  push:
    branches:
      - 'master'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    outputs:
      release_id: ${{ steps.release.outputs.releaseID }}

    steps:
      # See https://github.com/actions/checkout/releases
    - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      # See https://github.com/actions/setup-node/releases
    - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
      with:
        node-version: 20
    - name: Build and Package
      run: |
        yarn
        yarn package
    - name: Commit Changes
      # See https://github.com/planetscale/ghcommit-action/releases
      uses: planetscale/ghcommit-action@b662a9d7235a07e80d976152ed5afe41651c4973 # v0.1.43
      with:
        commit_message: "Update **/dist/index.js"
        repo: ${{ github.repository }}
        branch: ${{ github.head_ref || github.ref_name }}
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - id: hash
      run: |
        git fetch origin
        echo "hash=$(git rev-parse `git branch -r --sort=committerdate | tail -1`)" >> $GITHUB_OUTPUT
    - name: Make release
      id: release
      uses: ./release/
      with:
        appID: ${{ secrets.RELEASE_APP_ID }}
        appPrivateKey: ${{ secrets.RELEASE_APP_PK }}
        lastCommit: ${{ steps.hash.outputs.hash }}

  upload-logs:
    name: Upload Logs
    runs-on: ubuntu-latest
    needs: release

    steps:
    - uses: Kas-tle/release-build-log-action@1b57448eaf9476e6e05450e4ea240449eac2c0d2
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        releaseID: ${{ needs.release.outputs.release_id }}